export const CERTIFICATE_CATALOG = [
  {
    type: "friend",
    title: "Official Friend of the North Pole",
    description: "Awarded to children who begin a true friendship with an elf.",
    premium: false,
    unlockAfterLetters: 1,
  },
  {
    type: "best-friend",
    title: "Elf Best Friend Award",
    description: "For writing three heartfelt letters to your elf pal.",
    premium: false,
    unlockAfterLetters: 3,
  },
  {
    type: "nice-list",
    title: "Santa's Nice List Certificate",
    description: "A premium keepsake declaring a place on the Nice List.",
    premium: true,
    unlockAfterLetters: 2,
  },
  {
    type: "kindness",
    title: "Christmas Kindness Certificate",
    description: "Earned by playing games and spreading workshop cheer.",
    premium: false,
    unlockAfterGames: 2,
  },
  {
    type: "helper",
    title: "Santa's Helper Certificate",
    description: "For loyal helpers who keep the friendship glowing all season.",
    premium: false,
    unlockAfterLetters: 6,
  },
] as const;
export const VIDEO_SCENES = [
  {
    scene: "hello",
    title: "A Wave From the Workshop",
    description: "Your elf waves hello through swirling North Pole snow.",
    image: "/images/workshop.jpg",
    unlockAfter: 0,
  },
  {
    scene: "workshop",
    title: "Walking Through Santa's Workshop",
    description: "Tour the toy benches, ribbon spools, and glittering shelves.",
    image: "/images/workshop.jpg",
    unlockAfter: 1,
  },
  {
    scene: "tree",
    title: "Decorating the Tallest Tree",
    description: "Gold ornaments, candy canes, and a star that almost winks.",
    image: "/images/hero-northpole.jpg",
    unlockAfter: 1,
  },
  {
    scene: "reindeer",
    title: "Feeding the Reindeer",
    description: "Carrots, oats, and a nuzzle from a very famous herd.",
    image: "/images/reindeer-scene.jpg",
    unlockAfter: 2,
  },
  {
    scene: "delivery",
    title: "Delivering Toys",
    description: "A practice run with sleigh bells and a map of rooftops.",
    image: "/images/hero-northpole.jpg",
    unlockAfter: 3,
  },
  {
    scene: "snow",
    title: "Snowfall Over the North Pole",
    description: "Quiet magic as snow writes lace across the village.",
    image: "/images/hero-northpole.jpg",
    unlockAfter: 0,
  },
  {
    scene: "office",
    title: "Visiting Santa's Office",
    description: "The Nice List, the fireplace, and a secret wink from the desk.",
    image: "/images/santa-office.jpg",
    unlockAfter: 4,
  },
];
export const GAMES = [
  {
    slug: "spot-the-difference",
    title: "Elf Spot the Difference",
    description: "Find the sneaky changes in Santa's workshop.",
    icon: "🔍",
    difficulty: "Easy",
  },
  {
    slug: "word-search",
    title: "Christmas Word Search",
    description: "Hunt festive words hidden in the snowy grid.",
    icon: "🔤",
    difficulty: "Easy",
  },
  {
    slug: "elf-maze",
    title: "Elf Maze",
    description: "Guide your elf through candy-cane corridors.",
    icon: "🌀",
    difficulty: "Medium",
  },
  {
    slug: "hidden-objects",
    title: "Hidden Objects",
    description: "Spot lost toys, cocoa mugs, and tiny bells.",
    icon: "🎁",
    difficulty: "Medium",
  },
  {
    slug: "find-the-elf",
    title: "Find the Elf",
    description: "A Where's-Waldo-style search through the village.",
    icon: "🧝",
    difficulty: "Medium",
  },
  {
    slug: "match-presents",
    title: "Match the Presents",
    description: "Flip cards and match the wrapping paper pairs.",
    icon: "🎀",
    difficulty: "Easy",
  },
  {
    slug: "santa-memory",
    title: "Santa Memory Game",
    description: "Remember the workshop icons and find the pairs.",
    icon: "🎅",
    difficulty: "Easy",
  },
  {
    slug: "snowball-puzzle",
    title: "Snowball Puzzle",
    description: "Slide the tiles to restore a snowy picture.",
    icon: "❄️",
    difficulty: "Hard",
  },
  {
    slug: "coloring",
    title: "Christmas Coloring Pages",
    description: "Paint ornaments, elves, and trees with magic colors.",
    icon: "🎨",
    difficulty: "Easy",
  },
  {
    slug: "elf-trivia",
    title: "Elf Trivia",
    description: "How well do you know North Pole secrets?",
    icon: "⭐",
    difficulty: "Medium",
  },
];
export const PLANS = [
  {
    id: "monthly",
    name: "Monthly Unlimited Letters",
    price: 9.99,
    cadence: "month",
    blurb: "Unlimited letters, all games, and elf videos every month.",
    perks: [
      "Unlimited elf letters",
      "All mini games & badges",
      "Personalized video scenes",
      "Cancel anytime",
    ],
  },
  {
    id: "annual",
    name: "Annual Subscription",
    price: 79.99,
    cadence: "year",
    blurb: "A full year of North Pole magic plus a premium certificate.",
    perks: [
      "Everything in Monthly",
      "1 premium certificate included",
      "Birthday letter from your elf",
      "Priority workshop mail",
    ],
    featured: true,
  },
  {
    id: "lifetime",
    name: "Lifetime Membership",
    price: 199,
    cadence: "once",
    blurb: "One magical payment. Friendship that lasts every Christmas.",
    perks: [
      "Unlimited forever",
      "All premium certificates",
      "Christmas Eve letter",
      "Family sharing for siblings",
    ],
  },
];
export const ADDONS = [
  {
    id: "nice-list",
    name: "Nice List Certificate",
    price: 7.99,
    blurb: "A printable official Nice List keepsake.",
  },
  {
    id: "friendship",
    name: "Friendship Certificate",
    price: 6.99,
    blurb: "Gold-seal best-friend award, ready to print.",
  },
  {
    id: "video",
    name: "Personalized Video Message",
    price: 12.99,
    blurb: "A special workshop film starring your child's name.",
  },
  {
    id: "birthday",
    name: "Birthday Letter",
    price: 8.99,
    blurb: "A once-a-year birthday surprise from their elf.",
  },
  {
    id: "christmas-eve",
    name: "Christmas Eve Letter",
    price: 9.99,
    blurb: "Arrives in the inbox on December 24th.",
  },
  {
    id: "printed",
    name: "Printed Letter Mailed Home",
    price: 14.99,
    blurb: "A real parchment letter with a wax seal.",
  },
  {
    id: "gift-box",
    name: "Gift Box Upgrade",
    price: 24.99,
    blurb: "A festive box of treats and a keepsake ornament.",
  },
];
export const FREE_LETTER_LIMIT = 3;
export const KEYWORDS = [
  "Elf Pen Pal",
  "Letters from the North Pole",
  "Santa Letters",
  "Christmas App for Kids",
  "Elf Friend",
  "Santa Pen Pal",
  "Christmas Magic",
  "North Pole Letters",
  "Elf Mail",
  "Santa's Workshop",
];