export type ElfProfile = {
  id: string;
  name: string;
  gender: "boy" | "girl";
  bio: string;
  personality: string;
  hobbies: string;
  christmasJob: string;
  favoriteTreat: string;
  funFacts: string;
  greeting: string;
  catchphrase: string;
  hatColor: string;
  accentColor: string;
  skin: string;
  hair: string;
  hairStyle: "short" | "wavy" | "long" | "spiky" | "braids";
  eyes: string;
  accessory: "scarf" | "glasses" | "bells" | "holly" | "star" | "none";
  portrait?: string;
  voice: string[];
};
export const ELF_PROFILES: ElfProfile[] = [
  {
    id: "jingle",
    name: "Jingle",
    gender: "boy",
    bio: "Jingle is the workshop's official giggle captain. He can turn any gloomy morning into a snowball of giggles and never travels without a pocketful of tiny bells.",
    personality: "Funny, playful, and endlessly encouraging. Loves puns, sled races, and cheering kids on.",
    hobbies: "Sledding, inventing silly songs, racing toy trains",
    christmasJob: "Chief Toy Tester and Sled Coach",
    favoriteTreat: "Peppermint bark with extra crunch",
    funFacts: "Once sledded all the way from the workshop to the reindeer barn in 12 seconds. His hat bell is older than the North Pole bakery.",
    greeting: "Jingle bells, hello there!",
    catchphrase: "That's snow joke!",
    hatColor: "#C41E3A",
    accentColor: "#1B6B4A",
    skin: "#F6D2B1",
    hair: "#C45C26",
    hairStyle: "spiky",
    eyes: "#2E7D4F",
    accessory: "bells",
    portrait: "/images/elves/jingle.jpg",
    voice: [
      "Ha! That made my hat bell ring!",
      "Want to hear a snow pun? Of course you do.",
      "I just test-drove a toy sled. Ten out of ten whooshes!",
    ],
  },
  {
    id: "spark",
    name: "Spark",
    gender: "boy",
    bio: "Spark sprinkles glitter the way other elves sprinkle sugar. He is full of zip, zoom, and bright ideas that light up the wrapping room.",
    personality: "Energetic, optimistic, and a little sparkly. Always ready for an adventure.",
    hobbies: "Glitter experiments, firework-safe sparkle dust, wrapping presents at top speed",
    christmasJob: "Lead Present Wrapper",
    favoriteTreat: "Hot cocoa with cinnamon sparks",
    funFacts: "His mittens glow in the dark. He once wrapped 200 presents before lunch.",
    greeting: "Sparkle salute, friend!",
    catchphrase: "Let's make it shine!",
    hatColor: "#E8A317",
    accentColor: "#C41E3A",
    skin: "#E8B894",
    hair: "#3B2314",
    hairStyle: "short",
    eyes: "#C45C12",
    accessory: "star",
    voice: [
      "I added extra sparkle to the wrapping paper just for you.",
      "Zoom! That's the sound of Christmas magic arriving.",
      "If we believe big, the lights get brighter.",
    ],
  },
  {
    id: "frost",
    name: "Frost",
    gender: "boy",
    bio: "Frost is a quiet artist who sculpts ice swans and snowflakes no two alike. Kids trust him with secrets and wishes.",
    personality: "Calm, thoughtful, and gently funny. Speaks softly and notices everything.",
    hobbies: "Ice sculpting, stargazing, reading snowflake maps",
    christmasJob: "Nice List Scroll Keeper",
    favoriteTreat: "Blueberry snow cones",
    funFacts: "Can tell who sent a letter by the way the snow lands on the envelope. Owns 47 scarves.",
    greeting: "Hello, little snowflake.",
    catchphrase: "Every wish is worth keeping.",
    hatColor: "#6EC6FF",
    accentColor: "#E8F4FF",
    skin: "#F3D7C4",
    hair: "#D9E6F2",
    hairStyle: "wavy",
    eyes: "#3A7CA5",
    accessory: "glasses",
    portrait: "/images/elves/frost.jpg",
    voice: [
      "I saved a perfect snowflake to show you.",
      "The Nice List paper smells like pine today.",
      "Take a slow breath. Magic likes patience.",
    ],
  },
  {
    id: "twinkle",
    name: "Twinkle",
    gender: "boy",
    bio: "Twinkle paints ornaments with colors borrowed from the northern lights. He daydreams in constellations.",
    personality: "Dreamy, kind, and imaginative. Loves wondering about the sky.",
    hobbies: "Stargazing, ornament painting, cloud watching",
    christmasJob: "Ornament Artist",
    favoriteTreat: "Lemon star cookies",
    funFacts: "Named a star after his favorite paintbrush. Sleeps in socks with moons on them.",
    greeting: "A little star says hello!",
    catchphrase: "Look up — magic is glowing.",
    hatColor: "#5B2C6F",
    accentColor: "#F4D03F",
    skin: "#F0C8A0",
    hair: "#4A2C17",
    hairStyle: "wavy",
    eyes: "#6C3483",
    accessory: "star",
    voice: [
      "I mixed a new gold that looks like bedtime wishes.",
      "The aurora did a little dance last night.",
      "Your letter sparkled more than my glitter jar.",
    ],
  },
  {
    id: "cocoa",
    name: "Cocoa",
    gender: "boy",
    bio: "Cocoa runs the North Pole tasting kitchen and believes a warm mug can fix almost anything. He is huggable even from far away.",
    personality: "Warm, cozy, and generous. Always checking if you are comfortable.",
    hobbies: "Hot chocolate science, cookie dunking, telling kitchen stories",
    christmasJob: "Workshop Bakery Helper",
    favoriteTreat: "Giant marshmallows toasted just right",
    funFacts: "Invented peppermint-swirl cocoa. Has a mug for every day of December.",
    greeting: "Come in, it's cocoa time!",
    catchphrase: "Warm hearts, warm hands.",
    hatColor: "#6F4E37",
    accentColor: "#F5D0A9",
    skin: "#C68642",
    hair: "#2B1B12",
    hairStyle: "short",
    eyes: "#5D4037",
    accessory: "scarf",
    voice: [
      "I saved you the biggest marshmallow.",
      "The kitchen smells like cinnamon hugs today.",
      "If you ever feel chilly, write me. I'll send cozy thoughts.",
    ],
  },
  {
    id: "dash",
    name: "Dash",
    gender: "boy",
    bio: "Dash is a delivery scout who maps the fastest snowy routes. He has never missed a practice flight with the reindeer team.",
    personality: "Adventurous, brave, and loyal. Loves a good challenge.",
    hobbies: "Reindeer racing, map drawing, snowshoe sprints",
    christmasJob: "Sleigh Route Scout",
    favoriteTreat: "Gingerbread race cars",
    funFacts: "Can name every reindeer by the sound of their hooves. Sleeps in goggles sometimes.",
    greeting: "Ready, set, hello!",
    catchphrase: "Adventure is the best present.",
    hatColor: "#1B6B4A",
    accentColor: "#E8A317",
    skin: "#E0AC69",
    hair: "#1A1A1A",
    hairStyle: "spiky",
    eyes: "#1B4F72",
    accessory: "scarf",
    voice: [
      "Comet let me hold the reins for three whole seconds!",
      "I mapped a shortcut that smells like pine.",
      "You would make an excellent co-pilot.",
    ],
  },
  {
    id: "bells",
    name: "Bells",
    gender: "boy",
    bio: "Bells tunes every sleigh bell until it sings the right note. He hums carols while he works and invites everyone to join.",
    personality: "Musical, cheerful, and a little dramatic in the best way.",
    hobbies: "Caroling, drumming on cookie tins, writing jingles",
    christmasJob: "Sleigh Bell Tuner",
    favoriteTreat: "Candy canes snapped into rhythm sticks",
    funFacts: "Can play Jingle Bells on 14 different workshop tools. His laugh sounds like chimes.",
    greeting: "Ding-dong, it's me!",
    catchphrase: "Let's make some merry music.",
    hatColor: "#C41E3A",
    accentColor: "#F4D03F",
    skin: "#F1C27D",
    hair: "#7B3F00",
    hairStyle: "short",
    eyes: "#117A65",
    accessory: "bells",
    voice: [
      "I wrote a tiny song about your letter.",
      "The sleigh bells are in perfect tune tonight.",
      "If you hum along, the magic gets louder.",
    ],
  },
  {
    id: "pine",
    name: "Pine",
    gender: "boy",
    bio: "Pine is happiest among evergreen trees. He knows which spruce likes extra tinsel and talks to the forest like an old friend.",
    personality: "Gentle nature-lover, patient, and sturdy like a good tree.",
    hobbies: "Tree decorating, pinecone collecting, forest walks",
    christmasJob: "Christmas Tree Forest Scout",
    favoriteTreat: "Pine-and-honey cookies",
    funFacts: "Has a favorite tree named Big Green. Can identify 30 kinds of pinecones.",
    greeting: "The forest says hello!",
    catchphrase: "Stand tall and stay kind.",
    hatColor: "#0F4D3A",
    accentColor: "#C41E3A",
    skin: "#D2A679",
    hair: "#3E2723",
    hairStyle: "wavy",
    eyes: "#145A32",
    accessory: "holly",
    voice: [
      "I hung a new golden pinecone just for luck.",
      "The trees whispered that you have a kind heart.",
      "Fresh snow on evergreen is my favorite smell.",
    ],
  },
  {
    id: "glimmer",
    name: "Glimmer",
    gender: "boy",
    bio: "Glimmer invents toys that giggle, glow, or fold into secret surprises. His workbench is a delightful mess of gears and ribbon.",
    personality: "Inventive, curious, and proudly quirky.",
    hobbies: "Gadget making, puzzle boxes, midnight brainstorming",
    christmasJob: "Toy Inventor",
    favoriteTreat: "Caramel apples with tiny gears of chocolate",
    funFacts: "Built a robot that wraps hugs. Has ink on his nose most days.",
    greeting: "Idea incoming — hello!",
    catchphrase: "What if we invent the fun?",
    hatColor: "#2E86AB",
    accentColor: "#F4D03F",
    skin: "#E8C39E",
    hair: "#5D4E37",
    hairStyle: "spiky",
    eyes: "#1A5276",
    accessory: "glasses",
    voice: [
      "I sketched a toy inspired by your letter.",
      "Blueprints plus cocoa equals genius.",
      "You ask the best wondering questions.",
    ],
  },
  {
    id: "noel",
    name: "Noel",
    gender: "boy",
    bio: "Noel is the workshop storyteller. He keeps a lantern-lit nook of books and writes tales about brave, kind kids.",
    personality: "Kind, wise, and wonderfully story-minded.",
    hobbies: "Reading, writing bedtime tales, collecting postcards",
    christmasJob: "Story Workshop Keeper",
    favoriteTreat: "Sugar plums and cinnamon toast",
    funFacts: "Memorized 100 Christmas stories. Writes with a quill made from a snow goose feather.",
    greeting: "Once upon a hello...",
    catchphrase: "Every friend is a story worth telling.",
    hatColor: "#7B241C",
    accentColor: "#D4AF37",
    skin: "#F5CBA7",
    hair: "#4A235A",
    hairStyle: "wavy",
    eyes: "#6E2C00",
    accessory: "glasses",
    voice: [
      "I started a story where you are the hero.",
      "The lantern is lit and the page is waiting.",
      "Kindness is the plot twist that always wins.",
    ],
  },
  {
    id: "holly",
    name: "Holly",
    gender: "girl",
    bio: "Holly bakes cookies for tired reindeer and writes encouraging notes on every gift tag. She is the friend you want on a snowy afternoon.",
    personality: "Sweet, caring, and gently funny. Notices when someone needs a hug.",
    hobbies: "Baking cookies, braiding ribbon, feeding reindeer carrots",
    christmasJob: "Reindeer Caretaker and Cookie Baker",
    favoriteTreat: "Sugar cookies with holly icing",
    funFacts: "Dasher only eats her carrot muffins. She keeps a kindness jar that glows when it is full.",
    greeting: "Hello, sugarplum friend!",
    catchphrase: "A little kindness is Christmas magic.",
    hatColor: "#1B6B4A",
    accentColor: "#C41E3A",
    skin: "#F3C6A5",
    hair: "#8B3A2A",
    hairStyle: "wavy",
    eyes: "#5D4037",
    accessory: "holly",
    portrait: "/images/elves/holly.jpg",
    voice: [
      "I saved you a cookie with extra sprinkles.",
      "The reindeer asked me to send you a nuzzle.",
      "Your letter made the whole kitchen smell happier.",
    ],
  },
  {
    id: "ivy",
    name: "Ivy",
    gender: "girl",
    bio: "Ivy tends the North Pole greenhouse where winter roses and candy-cane mint grow side by side. She speaks softly to plants and people.",
    personality: "Gentle, patient, and quietly brave.",
    hobbies: "Wreath crafting, growing mint, pressing snowflowers",
    christmasJob: "Greenhouse Elf",
    favoriteTreat: "Peppermint tea with honey",
    funFacts: "Grew a poinsettia that sings. Wears boots with ivy embroidered on the toes.",
    greeting: "Hello from the greenhouse!",
    catchphrase: "Growing kindness takes sunshine and time.",
    hatColor: "#196F3D",
    accentColor: "#F5B7B1",
    skin: "#E0AC69",
    hair: "#1C2833",
    hairStyle: "long",
    eyes: "#1E8449",
    accessory: "holly",
    voice: [
      "A new mint leaf uncurled this morning. I named it after you.",
      "Wreaths are just hugs made of greenery.",
      "Even winter gardens believe in spring.",
    ],
  },
  {
    id: "snowflake",
    name: "Snowflake",
    gender: "girl",
    bio: "Snowflake catches unique flakes on velvet and studies their lace. She is shy at first and then the most loyal friend.",
    personality: "Shy-sweet, precise, and deeply loyal.",
    hobbies: "Catching snowflakes, ice-lace drawing, quiet tea parties",
    christmasJob: "Snow Decorator",
    favoriteTreat: "Vanilla ice cream in a snowball cup",
    funFacts: "Has never seen two matching snowflakes. Talks to the wind like a pen pal.",
    greeting: "Hi... I brought you a snowflake.",
    catchphrase: "You are one of a kind.",
    hatColor: "#D6EAF8",
    accentColor: "#85C1E9",
    skin: "#FDEBD0",
    hair: "#F7F9F9",
    hairStyle: "long",
    eyes: "#5DADE2",
    accessory: "none",
    voice: [
      "I caught a snowflake that looks like a tiny crown.",
      "It is okay to be quiet. Stars are quiet too.",
      "Your words feel like warm mittens.",
    ],
  },
  {
    id: "ruby",
    name: "Ruby",
    gender: "girl",
    bio: "Ruby leads the workshop dance after the last toy is boxed. She believes joy is a skill you can practice.",
    personality: "Bold, sparkly, and encouraging. Loves a stage and a friend in the front row.",
    hobbies: "Dancing, designing costumes, teaching jolly jigs",
    christmasJob: "Lead Dancer of Workshop Parties",
    favoriteTreat: "Cherry tarts with gold sugar",
    funFacts: "Can tap-dance on packed snow. Her shoes have secret bells.",
    greeting: "Ta-da! Hello, superstar!",
    catchphrase: "Shine like you mean it.",
    hatColor: "#922B21",
    accentColor: "#F4D03F",
    skin: "#C0392B",
    hair: "#1B0A00",
    hairStyle: "braids",
    eyes: "#7B241C",
    accessory: "star",
    voice: [
      "I invented a dance called The Letter Shuffle.",
      "You have main-character energy, my friend.",
      "When in doubt, add jazz hands and kindness.",
    ],
  },
  {
    id: "ginger",
    name: "Ginger",
    gender: "girl",
    bio: "Ginger is the cookie quality tester with a mischievous grin and flour on her nose. She knows 40 kinds of gingerbread houses.",
    personality: "Spunky, witty, and warm. Speaks in baking metaphors.",
    hobbies: "Baking, decorating gingerbread, taste-testing frosting",
    christmasJob: "Cookie Quality Tester",
    favoriteTreat: "Classic gingerbread with lemon glaze",
    funFacts: "Once built a gingerbread replica of the workshop. Keeps a lucky wooden spoon.",
    greeting: "Fresh from the oven — hello!",
    catchphrase: "Life's better with extra frosting.",
    hatColor: "#CA6F1E",
    accentColor: "#6E2C00",
    skin: "#F5CBA7",
    hair: "#A04000",
    hairStyle: "wavy",
    eyes: "#935116",
    accessory: "scarf",
    voice: [
      "I saved you the cookie that didn't break. That's the lucky one.",
      "Your letter was sweeter than molasses.",
      "If something feels crumbly, we rebuild it together.",
    ],
  },
  {
    id: "luna",
    name: "Luna",
    gender: "girl",
    bio: "Luna paints the night sky so the aurora has somewhere beautiful to dance. She writes letters by moonlight.",
    personality: "Magical, poetic, and reassuring. Loves mysteries and moonbeams.",
    hobbies: "Watching northern lights, night-sky painting, moonlit walks",
    christmasJob: "Night-Sky Painter",
    favoriteTreat: "Moon pies with silver sugar",
    funFacts: "Sleeps under a skylight. Claims the moon winks at good listeners.",
    greeting: "Moonlight mail for you!",
    catchphrase: "Believe in the glow you cannot see yet.",
    hatColor: "#1A237E",
    accentColor: "#CE93D8",
    skin: "#D7BDE2",
    hair: "#1C2833",
    hairStyle: "long",
    eyes: "#6C3483",
    accessory: "star",
    portrait: "/images/elves/luna.jpg",
    voice: [
      "The aurora wrote a green ribbon across the sky.",
      "I painted a tiny moon with your favorite color.",
      "Even the longest night keeps a lantern ready.",
    ],
  },
  {
    id: "merry",
    name: "Merry",
    gender: "girl",
    bio: "Merry writes the jokes that go inside Christmas crackers and can make Santa's mustache twitch with laughter.",
    personality: "Cheerful, silly, and bright. Spreads joy on purpose.",
    hobbies: "Joke writing, surprise parties, making paper crowns",
    christmasJob: "Official Joke Writer",
    favoriteTreat: "Fudge squares stacked like presents",
    funFacts: "Knows 200 knock-knock jokes. Once made a snowman laugh. (She swears.)",
    greeting: "Knock knock — it's Merry!",
    catchphrase: "Giggle first, then everything else.",
    hatColor: "#C0392B",
    accentColor: "#27AE60",
    skin: "#F9E79F",
    hair: "#F5B041",
    hairStyle: "spiky",
    eyes: "#1ABC9C",
    accessory: "bells",
    voice: [
      "Knock knock. Who's there? Holly. Holly who? Holly-days are better with you!",
      "I put a joke in a cracker with your name on it.",
      "Your smile is my favorite decoration.",
    ],
  },
  {
    id: "willow",
    name: "Willow",
    gender: "girl",
    bio: "Willow speaks fluent reindeer and keeps a pocket of oats for any creature that looks hungry. She is soft-spoken and very brave.",
    personality: "Soft-spoken, animal-loving, and brave in quiet ways.",
    hobbies: "Animal care, snow tracking, weaving oat-straw stars",
    christmasJob: "Reindeer Caretaker",
    favoriteTreat: "Honey cakes with clover",
    funFacts: "Blitzen nuzzles her first every morning. She can calm a startled fawn in a whisper.",
    greeting: "The reindeer send nuzzles!",
    catchphrase: "Gentle is a superpower.",
    hatColor: "#7D6608",
    accentColor: "#1B6B4A",
    skin: "#EDBB99",
    hair: "#6E2C00",
    hairStyle: "braids",
    eyes: "#196F3D",
    accessory: "holly",
    voice: [
      "Prancer practiced a bow just for you.",
      "I braided a tiny straw star into Vixen's harness.",
      "Being gentle with animals makes the whole Pole kinder.",
    ],
  },
  {
    id: "stella",
    name: "Stella",
    gender: "girl",
    bio: "Stella organizes gift tags so every present finds the right hands. She loves lists, gold pens, and perfectly tied bows.",
    personality: "Bright, organized, and encouraging. Turns chaos into sparkle.",
    hobbies: "Gift-tag art, gold-ink lettering, making checklists fun",
    christmasJob: "Gift-Tag Artist",
    favoriteTreat: "Cinnamon rolls with star sprinkles",
    funFacts: "Never loses a ribbon. Her checklists have glitter bullets.",
    greeting: "Checked you off the hello list!",
    catchphrase: "Little plans make big magic.",
    hatColor: "#B7950B",
    accentColor: "#922B21",
    skin: "#F5CBA7",
    hair: "#4A235A",
    hairStyle: "wavy",
    eyes: "#B9770E",
    accessory: "star",
    voice: [
      "I wrote your name in gold ink. It looked extra official.",
      "A tidy bow can hold a lot of love.",
      "You are doing wonderfully. Star sticker earned.",
    ],
  },
  {
    id: "pearl",
    name: "Pearl",
    gender: "girl",
    bio: "Pearl mentors the youngest elves and remembers everyone's birthday. She is wise without ever being bossy.",
    personality: "Wise, nurturing, and twinkly-eyed. A natural teacher.",
    hobbies: "Mentoring, tea parties, collecting snow-pearls",
    christmasJob: "Workshop Mentor",
    favoriteTreat: "Vanilla snowball cookies",
    funFacts: "Has a pearl button from the first workshop apron. Reads letters twice so she never misses a feeling.",
    greeting: "Welcome, dear friend.",
    catchphrase: "You already have what you need inside.",
    hatColor: "#F8F4E3",
    accentColor: "#AD1457",
    skin: "#F6D7B0",
    hair: "#85929E",
    hairStyle: "long",
    eyes: "#5D6D7E",
    accessory: "glasses",
    voice: [
      "I am proud of you, and I do not say that lightly.",
      "Even grown-up elves still practice being kind.",
      "Your questions make me a better teacher.",
    ],
  },
];
export function getElf(id: string) {
  return ELF_PROFILES.find((elf) => elf.id === id) ?? ELF_PROFILES[0];
}
export const BOY_ELVES = ELF_PROFILES.filter((elf) => elf.gender === "boy");
export const GIRL_ELVES = ELF_PROFILES.filter((elf) => elf.gender === "girl");
